### ISSUE TITLE
Multiple identical select raised in a JHipster project

### ISSUE THREAD

**Issue by anthonyrichir** [quick-perf/quickperf#38] opened 2020-01-07 15:58 UTC
Hello,

I'm trying to use QuickPerf within a Jhipster project in which I get an error with QuickPerf stating that I have 2 times the same select statement.

However, I don't think it's the case.

Here is the sample project I'm using to prove my point https://github.com/anthonyrichir/quickperf-sample-test.

For instance, a test on the repository itself:
```java
@Import(QuickPerfPerBeanConfig.class)
@SpringBootTest(classes = BookApiApp.class)
@QuickPerfTest
class BookRepositoryTest {

    @Autowired
    private BookRepository bookRepository;

	@Test
    @ExpectSelect(1)
	void findAllWithEagerRelationships() {
        bookRepository.findAllWithEagerRelationships();
	}

	@Test
    @ExpectSelect(1)
	void findOneWithEagerRelationships() {
	    bookRepository.findOneWithEagerRelationships(1L);
	}
}
```

Where the repository is:
```java
@Repository
public interface BookRepository extends JpaRepository<Book, Long> {

    @Query(value = "select distinct book from Book book left join fetch book.authors",
        countQuery = "select count(distinct book) from Book book")
    Page<Book> findAllWithEagerRelationships(Pageable pageable);

    @Query("select distinct book from Book book left join fetch book.authors")
    List<Book> findAllWithEagerRelationships();

    @Query("select book from Book book left join fetch book.authors where book.id =:id")
    Optional<Book> findOneWithEagerRelationships(@Param("id") Long id);

}
```

Will produce this output.
```
[WARNING] QuickPerf has built several datasource proxies


java.lang.AssertionError: a performance property is not respected

[PERF] You may think that <1> select request was sent to the database
       But in fact <2>...

You may decrease the number of select requests in order to reduce the cost of
server roundtrips: https://blog.jooq.org/2017/12/18/the-cost-of-jdbc-server-roundtrips/

Perhaps you are facing a N+1 select issue
	* With Hibernate, you may fix it by using JOIN FETCH
	                                       or LEFT JOIN FETCH
	                                       or FetchType.LAZY
	                                       or ...
	  Some examples: https://stackoverflow.com/questions/32453989/what-is-the-solution-for-the-n1-issue-in-jpa-and-hibernate";
	                 https://thoughts-on-java.org/jpa-21-entity-graph-part-1-named-entity/

	* With Spring Data JPA, you may fix it by adding
	@EntityGraph(attributePaths = { "..." }) on repository method.
	https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.entity-graph

[SQL EXECUTIONS]
	Time:0, Success:True, Type:Prepared, Batch:False, QuerySize:1, BatchSize:0, Query:["
    select
        distinct book0_.id as id1_1_0_,
        author2_.id as id1_0_1_,
        book0_.editor_id as editor_i3_1_0_,
        book0_.name as name2_1_0_,
        book0_.owner_id as owner_id4_1_0_,
        author2_.name as name2_0_1_,
        authors1_.book_id as book_id1_2_0__,
        authors1_.author_id as author_i2_2_0__ 
    from
        book book0_ 
    left outer join
        book_author authors1_ 
            on book0_.id=authors1_.book_id 
    left outer join
        author author2_ 
            on authors1_.author_id=author2_.id"], Params:[()]

	Time:1, Success:True, Type:Prepared, Batch:False, QuerySize:1, BatchSize:0, Query:["
    select
        distinct book0_.id as id1_1_0_,
        author2_.id as id1_0_1_,
        book0_.editor_id as editor_i3_1_0_,
        book0_.name as name2_1_0_,
        book0_.owner_id as owner_id4_1_0_,
        author2_.name as name2_0_1_,
        authors1_.book_id as book_id1_2_0__,
        authors1_.author_id as author_i2_2_0__ 
    from
        book book0_ 
    left outer join
        book_author authors1_ 
            on book0_.id=authors1_.book_id 
    left outer join
        author author2_ 
            on authors1_.author_id=author2_.id"], Params:[()]
```

Is it due to the several datasource proxies message ?

**Comment by jeanbisutti** [comment] 2020-01-07 21:48
Hello,

I confirm that select statements are duplicated and that the issue is related to data source proxies message.

To fix it, in  `QuickPerfProxyBeanPostProcessor` class you can replace

``` java
    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName) {

        if (bean instanceof DataSource) {
```
by
``` java
    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName) {

       if (bean instanceof DataSource && !(bean.toString().contains("ProxyDataSource"))) {
```

In ` BookResourceIT`  class you can remove 
``` java
@Import(QuickPerfPerBeanConfig.class)
``` 
The QuickPerf configuration with JUnit 5 and Spring will be easier in the next QuickPerf release (it won't be needed to define the ` QuickPerfProxyBeanPostProcessor`  class in your project).

**Comment by anthonyrichir** [comment] 2020-01-08 10:58
Thanks, it's working !

But I broke the code again :)

So if you now look at the code, I changed the `BookResource` class where the `getUser` was using an eager fetch method. Now I'm using the default `findById` and it seems that QuickPerf doesn't consider the query to be part of the test body.
```java
    @GetMapping("/books/{id}")
    @Transactional(readOnly = true)
    public ResponseEntity<Book> getBook(@PathVariable Long id) {
        log.debug("REST request to get Book : {}", id);
        Optional<Book> book = bookRepository.findById(id);
        return ResponseUtil.wrapOrNotFound(book);
    }
```
I also added the `@Transactional` annotation (I don't know why Jhipster doesn't generate them) but it has no impact.

The output of the test is the following with `displaySqlOfTestMethodBody` configured.
```
Hibernate: insert into book (id, editor_id, name, owner_id) values (null, ?, ?, ?)


java.lang.AssertionError: a performance property is not respected

[PERF] You may think that <1> select request was sent to the database
       But in fact <0>...

[SQL EXECUTIONS]
	Time:1, Success:True, Type:Prepared, Batch:False, QuerySize:1, BatchSize:0, Query:["
    insert 
    into
        book
        (id, editor_id, name, owner_id) 
    values
        (null, ?, ?, ?)"], Params:[(NULL(BIGINT),AAAAAAAAAA,NULL(BIGINT))]
```
You can also note that with `show-sql: true`, it only outputs the insert statement in the Hibernate logs.
So I guess it's not a problem with QuickPerf. Do you have any idea why ?

**Comment by anthonyrichir** [comment] 2020-01-08 11:09
Ok, I manage to solve it by clearing the persistence context right after saving the entity in the test.

```java
@Test
    @Transactional
    @ExpectSelect(1)
    public void getBook() throws Exception {
        // Initialize the database
        bookRepository.saveAndFlush(book);

        em.clear();

        // Get the book
        restBookMockMvc.perform(get("/api/books/{id}", book.getId()))
            .andExpect(status().isOk())
            .andExpect(content().contentType(MediaType.APPLICATION_JSON_UTF8_VALUE))
            .andExpect(jsonPath("$.id").value(book.getId().intValue()))
            .andExpect(jsonPath("$.name").value(DEFAULT_NAME.toString()));
    }
```
I've made several tests and I have the feeling that a repository method with `@Query` always goes to the database, skipping the persistence context.

**Comment by jeanbisutti** [comment] 2020-01-08 21:27
@anthonyrichir , if you need help on QuickPerf don't hesitate to open question issues

**Comment by jeanbisutti** [comment] 2020-01-31 18:39
Fixed with d4bde6601ad1fdd981ffcc7c172c929f431eb18f
Snaphot version deployed

**Comment by jeanbisutti** [comment] 2020-02-07 12:57
@anthonyrichir I created a PR (https://github.com/anthonyrichir/quickperf-sample-test/pull/2) to uprade your project to QuickPerf 1.0.0-RC6 and to simplify the configuration

**Comment by jeanbisutti** [comment] 2020-02-07 12:59
@anthonyrichir If you  want contribute, for example by explaining how to add QuickPerf just after having created a JHipster project, you are very welcome

**Closed by jeanbisutti** 2020-02-07 12:59 UTC
Labels: :bug: bug, junit5

**Comment by anthonyrichir** [comment] 2020-02-08 08:33
Thanks for your feedback !
